# This script will animate PNG files generated by the PSK Reporter plotter scripts into a GIF file.
# Uncomment the method below you would like to use to create the GIF.

# Method 1: Using ImageMagick
#magick convert -delay 20 -loop 0 ./plots/*.png ./plots/PSKR-anmiation.gif

# Method 2: Using ffmpeg
#ffmpeg -framerate 6 -pattern_type glob -i './plots/*.png' ./plots/PSKR-animation.gif

# The PNG files are large in size dimension wise, 2850 pixels wide by default.
# The ffmpeg command will resize the images to 1920 pixels wide while maintaining the aspect ratio.
# Set the framerate as you see fit.

# Creates a gigantic GIF file.
#ffmpeg -framerate 6 -pattern_type glob -i './plots/*.png' -vf "scale=1920:-1" ./plots/PSKR-animation.gif

# Creates a MKV video file in H.265 encoding. 12 frames per second.
#ffmpeg -framerate 12 -pattern_type glob -i '*.png' -vf "scale=1920:-1" -preset medium -c:v libx265 PSKR-animation-12fps.mkv

# Creates a MP4 video file in H.265 encoding. 12 frames per second.
#ffmpeg -framerate 12 -pattern_type glob -i '*.png' -vf "scale=1920:-1" -preset medium -c:v libx265 PSKR-animation-12fps.mp4

# Creates an MP4 video file in H.264 encoding. 12 frames per second.
#ffmpeg -framerate 12 -pattern_type glob -i '*.png' -vf "scale=1920:-1" -preset medium -c:v libx264 PSKR-animation-12fps-h264.mp4